export const data=[
	{
		"id": "15f76ea5-4b78-47e9-9621-4bb9d12a1b86",
		"title": "10th Multi-stakeholder Forum on Science, Technology and Innovation for the Sustainable Development Goals",
		"description": "The tenth annual Multi-Stakeholder Forum on Science, Technology and Innovation for the SDGs (STI Forum) will be held at the United Nations Headquarters in New York from 7 to 8 May 2025. It will be con...",
		"url": "https://sdgs.un.org/tfm/STIForum2025",
		"author": "sdgs.un.org",
		"image": "https://sdgs.un.org/themes/custom/porto/favicon.ico",
		"language": "en",
		"category": ["economy"],
		"published": "2025-05-07 09:13:04 +0000"
	},
	{
		"id": "0d6b3b19-47df-40c4-ba1d-0b66f854d67c",
		"title": "Parkinson's patients who take 'magic mushrooms' see key benefits, study finds",
		"description": "As Parkinson's cases continue to rise, the race is on for therapies to combat the effects of the disease — and researchers have pinpointed an unlikely source of relief.Psilocybin, a psychedelic compound found in some mushrooms, has been found to improve mood, cognition and motor symptoms in Parkinso...",
		"url": "https://www.foxnews.com/health/parkinsons-patients-who-take-magic-mushrooms-see-key-benefits-study-finds",
		"author": "foxnews",
		"image": "https://static.foxnews.com/foxnews.com/content/uploads/2025/05/holding-mushrooms.jpg",
		"language": "en",
		"category": ["health", "lifestyle"],
		"published": "2025-05-07 09:00:48 +0000"
	},
	{
		"id": "cbdf6e62-df48-4bbd-bf7d-d4851a2d913a",
		"title": "Second Navy fighter jet goes overboard from Truman aircraft carrier, pilots ejected",
		"description": "Two U.S. Navy pilots ejected while attempting to land a fighter jet on an aircraft carrier on Tuesday, resulting in the aircraft being lost in the Red Sea, the second such incident in a week, Department of Defense officials said. An F/A-18F Super Hornet, attached to Strike Fighter Squadron (VFA) 11,...",
		"url": "https://www.foxnews.com/us/second-navy-fighter-jet-goes-overboard-from-truman-aircraft-carrier-pilots-ejected",
		"author": "foxnews",
		"image": "https://static.foxnews.com/foxnews.com/content/uploads/2025/03/uss-harry-s.-truman-2.jpg",
		"language": "en",
		"category": ["general"],
		"published": "2025-05-07 05:55:33 +0000"
	},
	{
		"id": "fde1c9be-f9cc-491f-968b-4df7e6b23698",
		"title": "Pet raccoon caught with meth pipe in its mouth when cops pulled over Ohio woman: 'Expect the unexpected'",
		"description": "A raccoon with a meth pipe in its mouth was found in the front seat of a car when police in Ohio conducted a traffic stop that led to the discovery of a woman's supply of drugs.Springfield Township Police pulled over Victoria Vidal, 55, on Monday for an active warrant and a suspended driver's licens...",
		"url": "https://www.foxnews.com/us/pet-raccoon-caught-meth-pipe-its-mouth-when-cops-pulled-over-ohio-woman-expect-unexpected",
		"author": "foxnews",
		"image": "https://static.foxnews.com/foxnews.com/content/uploads/2025/05/raccoon.png",
		"language": "en",
		"category": ["general"],
		"published": "2025-05-07 05:31:03 +0000"
	},
	{
		"id": "6b086ec2-e2a9-46f5-9d59-450ba2cd104c",
		"title": "Trump slams Newsom after California governor proposes federal film tax credit to \"Make America Film Again\"",
		"description": "President Trump slammed Gavin Newsom on Tuesday, just hours after the California governor asked for collaboration on a massive national film tax credit.",
		"url": "https://www.cbsnews.com/news/president-trump-gavin-newsom-film-tariffs-tax-credit/",
		"author": "cbsnews",
		"image": "https://assets3.cbsnewsstatic.com/hub/i/r/2025/05/07/c87e1c6f-6a80-4bf5-923b-85c8edfd294d/thumbnail/1200x630/0cf31b28b951ec110d1235b3f4713a40/gettyimages-2207065545.jpg?v=8782d831dd587e69db5d043c0a4c5f4b",
		"language": "en",
		"category": ["politics", "world"],
		"published": "2025-05-07 05:20:00 +0000"
	},
	{
		"id": "08b399a2-c436-4539-9f40-70c29695ccff",
		"title": "Karen Read's voicemails to John O'Keefe played in murder trial: 'I f---ing hate you'",
		"description": "\"John, I f---ing hate you,\" Karen Read allegedly told her boyfriend, Boston Police Officer John O'Keefe, a minute after walking into his house without him.It was the morning he died, and she had just driven there from the crime scene, according to Massachusetts investigators.Special prosecutor Hank ...",
		"url": "https://www.foxnews.com/us/karen-reads-voicemails-john-okeefe-played-murder-trial-i-hate-you",
		"author": "foxnews",
		"image": "https://static.foxnews.com/foxnews.com/content/uploads/2025/05/karen-read-boston-ma-retrial-john-okeefe-day-10-12.jpg",
		"language": "en",
		"category": ["general"],
		"published": "2025-05-07 04:00:20 +0000"
	},
	{
		"id": "6671e87c-1a2c-448e-9383-aa68c544779a",
		"title": "Trump administration may soon deport migrants to Libya, U.S. officials say",
		"description": "The Trump administration may soon start deporting migrants to Libya, expanding its mass deportation campaign to the troubled North African country, two U.S. officials told CBS News Tuesday.\n\nThe depor...",
		"url": "https://www.cbsnews.com/news/trump-administration-may-soon-deport-migrants-to-libya/",
		"author": "Camilo",
		"image": "https://assets2.cbsnewsstatic.com/hub/i/r/2025/05/07/0b1107c6-0bc4-44ef-91ae-32185d073931/thumbnail/1200x630/6a1893cd18cb232935b30c1694078db5/gettyimages-2211891216.jpg?v=8782d831dd587e69db5d043c0a4c5f4b",
		"language": "en",
		"category": ["politics", "world"],
		"published": "2025-05-07 03:24:00 +0000"
	},
	{
		"id": "db178759-3eb8-45f2-a5fb-5bfd197345f2",
		"title": "Tyrese Haliburton makes last-second 3 to complete Pacers' wild comeback, take surprising 2-0 lead over Cavs",
		"description": "Advantage, Indiana Pacers.The Pacers, fourth in the Eastern Conference, entered their second-round series against the top-seeded Cleveland Cavaliers as heavy underdogs. But suddenly, the ball is in their court.After upsetting Cleveland Game 1, they overcame a 20-point deficit thanks to Tyrese Halibu...",
		"url": "https://www.foxnews.com/sports/tyrese-haliburton-makes-last-second-3-complete-pacers-wild-comeback-take-surprising-2-0-lead-over-cavs",
		"author": "foxnews",
		"image": "https://static.foxnews.com/foxnews.com/content/uploads/2025/05/haliburton.jpg",
		"language": "en",
		"category": ["general"],
		"published": "2025-05-07 03:00:41 +0000"
	},
	{
		"id": "d58eb73e-827c-4071-b9a8-539bfae5f608",
		"title": "For second time in 8 days, U.S. fighter jet assigned to USS Truman is lost in Red Sea",
		"description": "U.S. fighter jet assigned to the USS Harry S. Truman lost in Red Sea\n\nFor the second time in just over a week, an F/A-18E Super Hornet fighter jet assigned to the USS Harry S. Truman has been lost in ...",
		"url": "https://www.cbsnews.com/news/u-s-fighter-jet-assigned-to-uss-truman-lost-red-sea-second-time/",
		"author": "Eleanor",
		"image": "https://assets2.cbsnewsstatic.com/hub/i/r/2019/07/31/85362f2f-252f-4d0c-a88a-1671a98c99a6/thumbnail/1200x630/2f23167bb1d44538d9853a06571f025e/S112426552.jpg?v=8782d831dd587e69db5d043c0a4c5f4b",
		"language": "en",
		"category": ["politics", "world"],
		"published": "2025-05-07 02:49:46 +0000"
	},
	{
		"id": "6dd90ca1-b446-44cc-8250-9c9bb2bb3f2c",
		"title": "Blue city mayor says ICE arrests of dangerous criminals are not ‘focused on making us safer’",
		"description": "U.S. Immigration and Customs Enforcement (ICE) conducted operations in Nashville this week, resulting in the arrests of a convicted child sex predator and an alleged gang member, but the mayor of the city said the arrests were not focused on making the city safer.The Department of Homeland Security ...",
		"url": "https://www.foxnews.com/us/blue-city-mayor-says-ice-arrests-dangerous-criminals-not-focused-making-us-safer",
		"author": "foxnews",
		"image": "https://static.foxnews.com/foxnews.com/content/uploads/2025/05/nashville-mayor-ice.jpg",
		"language": "en",
		"category": ["general"],
		"published": "2025-05-07 02:14:27 +0000"
	},
	{
		"id": "107835af-9698-4edc-b7d3-529200c4b28e",
		"title": "Cavs coach Kenny Atkinson calls out Pacers, suggests team crossed 'line of physicality' in playoff game",
		"description": "The Cleveland Cavaliers entered this year's playoffs as the top seed in the Eastern Conference then cruised through a first-round series with the Miami Heat.After sweeping the Heat, the Cavs opened a second-round series with the Indiana Pacers Sunday. The Pacers upset the Cavs in Game 1 of the East ...",
		"url": "https://www.foxnews.com/sports/cavs-coach-kenny-atkinson-calls-out-pacers-suggests-team-crossed-line-physicality-playoff-game",
		"author": "foxnews",
		"image": "https://static.foxnews.com/foxnews.com/content/uploads/2025/05/kenny-atkinson.jpg",
		"language": "en",
		"category": ["general"],
		"published": "2025-05-07 02:01:28 +0000"
	},
	{
		"id": "3a5d4b64-ac97-47e4-9fa7-17240148b57f",
		"title": "Yankees legend Derek Jeter makes crucial life message hilarious in speech to Michigan graduates",
		"description": "Derek Jeter delivered the commencement speech at the University of Michigan Saturday and spoke about the importance of fighting through failure. The New York Yankees legend would've played baseball at Michigan, the state he called home in Kalamazoo, if he didn't turn pro right away as a first-round ...",
		"url": "https://www.foxnews.com/sports/yankees-legend-derek-jeter-makes-crucial-life-message-hilarious-speech-michigan-graduates",
		"author": "foxnews",
		"image": "https://static.foxnews.com/foxnews.com/content/uploads/2022/09/Derek-Jeter2.jpg",
		"language": "en",
		"category": ["general"],
		"published": "2025-05-07 01:42:50 +0000"
	},
	{
		"id": "ea53ce81-82d9-42a6-b67b-64aceb9c7ecb",
		"title": "Noem calls for the death penalty following maritime human smuggling attempt that left child dead",
		"description": "Homeland Security Secretary Kristin Noem called for the death penalty in the wake of a disastrous maritime human smuggling operation that left one child, and at least two others, dead.The U.S. Attorney's Office for the Southern District of California announced charges Tuesday against five illegals i...",
		"url": "https://www.foxnews.com/politics/five-illegals-charged-alleged-maritime-human-smuggling-attempt-left-child-dead",
		"author": "foxnews",
		"image": "https://static.foxnews.com/foxnews.com/content/uploads/2025/05/border-patrol-san-diego.png",
		"language": "en",
		"category": ["general"],
		"published": "2025-05-07 01:29:12 +0000"
	},
	{
		"id": "4649148a-752d-4611-93c7-fd7d0f518e67",
		"title": "Pirates security guard whips fan with belt during stadium fight and gets suspended",
		"description": "A Pittsburgh Pirates stadium usher has been suspended after being seen using his belt to whip a fan during a fistfight at PNC Park on Sunday.The video begins by showing the usher and fan standing face-to-face in a heated argument before the staffer punches the fan in the face multiple times. CLICK H...",
		"url": "https://www.foxnews.com/sports/pirates-security-guard-whips-fan-belt-during-stadium-fight-gets-suspended",
		"author": "foxnews",
		"image": "https://static.foxnews.com/foxnews.com/content/uploads/2023/06/Pirates-hat.jpg",
		"language": "en",
		"category": ["general"],
		"published": "2025-05-07 01:04:15 +0000"
	},
	{
		"id": "935b039e-d09d-4169-a9f6-3830bdbe54b3",
		"title": "'The View' co-host insists Gloria Gaynor is actually a feminist after singer rejects title",
		"description": "The ladies of \"The View\" tried to make sense of why Gloria Gaynor does not consider her iconic song, \"I Will Survive,\" to be a feminist anthem and why she would not label herself a feminist.In a recent interview with the UK outlet Metro, Gaynor said that one of the biggest misconceptions about her i...",
		"url": "https://www.foxnews.com/media/the-view-co-host-insists-gloria-gaynor-actually-feminist-after-singer-rejects-title",
		"author": "foxnews",
		"image": "https://static.foxnews.com/foxnews.com/content/uploads/2025/05/gloria-gaynor.jpg",
		"language": "en",
		"category": ["general"],
		"published": "2025-05-07 01:00:35 +0000"
	},
	{
		"id": "bd97fbb9-4f6c-4914-8cc7-965a038baf78",
		"title": "Astounding new audio shows air traffic controllers reacting to FAA tech outage: 'This is a serious issue'",
		"description": "Incredible air traffic control (ATC) audio captures the moment staff lost radar and radio signals while guiding planes to Newark Liberty International Airport in New Jersey last week.The April 28 outage lasted roughly 90 seconds. The National Air Traffic Controllers Association confirmed the inciden...",
		"url": "https://www.foxnews.com/travel/astounding-new-audio-shows-air-traffic-controllers-reacting-faa-tech-outage-this-serious-issue",
		"author": "foxnews",
		"image": "https://static.foxnews.com/foxnews.com/content/uploads/2025/05/newark-tower.jpg",
		"language": "en",
		"category": ["general"],
		"published": "2025-05-07 00:53:28 +0000"
	},
	{
		"id": "232d630a-f579-4729-8a74-96137c3148da",
		"title": "Scott Bessent says US doesn't want to decouple from China ahead of scheduled meeting with Chinese counterpart",
		"description": "Treasury Secretary Scott Bessent and U.S. Trade Representative Jamieson Greer will meet with their Chinese counterparts over the weekend in Switzerland to discuss economic matters, a significant first step in trade talks between the two global superpowers since President Donald Trump announced sweep...",
		"url": "https://www.foxnews.com/media/scott-bessent-says-us-doesnt-want-decouple-from-china-ahead-scheduled-meeting-chinese-counterpart",
		"author": "foxnews",
		"image": "https://static.foxnews.com/foxnews.com/content/uploads/2025/05/treasury-sec-scott-bessent.png",
		"language": "en",
		"category": ["general"],
		"published": "2025-05-07 00:53:08 +0000"
	},
	{
		"id": "e6c0337d-68d5-4467-8396-ed47694e3640",
		"title": "Trump says less than 2 dozen hostages believed to be alive in Gaza",
		"description": "What we know about Israel's plans to capture the entire Gaza Strip\n\nWhat we know about Israel's plans to capture Gaza\n\nWhat we know about Israel's plans to capture Gaza\n\nPresident Trump said Tuesday t...",
		"url": "https://www.cbsnews.com/news/trump-says-less-than-2-dozen-hostages-believed-to-be-alive-in-gaza/",
		"author": "cbsnews",
		"image": "https://assets2.cbsnewsstatic.com/hub/i/r/2025/05/07/0f9f983c-8c4b-4cca-b7a1-4f51038547a3/thumbnail/1200x630/12c8cf6ba5b5384629818cd2f3352bc1/gettyimages-2213213417.jpg?v=8782d831dd587e69db5d043c0a4c5f4b",
		"language": "en",
		"category": ["politics", "world"],
		"published": "2025-05-07 00:42:28 +0000"
	},
	{
		"id": "ddc40d9d-770c-47f3-8a26-a2c0169bcb60",
		"title": "Ex-NFL player speaks out against college athlete revenue sharing with landmark Supreme Court ruling pending",
		"description": "The age of athlete compensation in college sports could get a lot more complicated with a pending Supreme Court decision. A settlement in the case of House v. NCAA would allow all Division I schools to share revenue directly with student athletes if it receives final approval this month.The current ...",
		"url": "https://www.foxnews.com/sports/ex-nfl-player-speaks-out-against-college-athlete-revenue-sharing-landmark-supreme-court-ruling-pending",
		"author": "foxnews",
		"image": "https://static.foxnews.com/foxnews.com/content/uploads/2025/02/supreme-court.jpg",
		"language": "en",
		"category": ["general"],
		"published": "2025-05-07 00:37:54 +0000"
	},
	{
		"id": "8f2d7933-0c0b-4b97-a36f-68b5aeb1bca2",
		"title": "DeSantis signs bill banning fluoride additives in Florida public water: 'Hydrate, not medicate'",
		"description": "Florida Gov. Ron DeSantis signed SB 700 into law Tuesday, eliminating the ability of local governments to add fluoride or other medical additives to the state's public water supply, a move cheered by supporters of medical freedom and health transparency.\"Jamming fluoride in the water supply …  is es...",
		"url": "https://www.foxnews.com/health/desantis-signs-bill-banning-fluoride-additives-florida-public-water-hydrate-not-medicate",
		"author": "foxnews",
		"image": "https://static.foxnews.com/foxnews.com/content/uploads/2025/05/desantis-fluoride.jpg",
		"language": "en",
		"category": ["health", "lifestyle"],
		"published": "2025-05-07 00:20:06 +0000"
	},
	{
		"id": "de5f9ab5-ef29-4f48-9f4f-934f7fff0544",
		"title": "Canada's new prime minister pushes back at Trump in Oval Office meeting",
		"description": "Canada's new prime minister pushes back at Trump in Oval Office meeting For months, President Trump has taunted Canada by claiming it should become America's 51st state. But the country's new prime mi...",
		"url": "https://www.cbsnews.com/video/canadas-new-prime-minister-pushes-back-at-trump-in-oval-office-meeting/",
		"author": "cbsnews",
		"image": "https://assets3.cbsnewsstatic.com/hub/i/r/2025/05/07/e3dcd3ac-fb58-4c45-bb84-b0f912e5b7da/thumbnail/1200x630/b722c0385fba3de69bd14038ad824973/cbsn-fusion-canadas-new-prime-minister-pushes-back-at-trump-in-oval-office-meeting-thumbnail.jpg?v=8782d831dd587e69db5d043c0a4c5f4b",
		"language": "en",
		"category": ["politics", "world"],
		"published": "2025-05-07 00:10:00 +0000"
	},
	{
		"id": "41bb96c3-9f53-4bb1-944c-5c01fb754e57",
		"title": "Trump expresses 'absolute confidence' as Steve Witkoff is sworn in as special Middle East envoy",
		"description": "President Donald Trump's new special envoy to the Middle East was sworn in by Secretary of State Marco Rubio Tuesday in an Oval Office ceremony.Speaking before the swearing-in, Trump praised Witkoff, who was instrumental in securing an extended ceasefire between Israel and Hamas and the return of 33...",
		"url": "https://www.foxnews.com/politics/trump-expresses-absolute-confidence-steve-witkoff-sworn-special-middle-east-envoy",
		"author": "foxnews",
		"image": "https://static.foxnews.com/foxnews.com/content/uploads/2025/05/witkoff-trump.png",
		"language": "en",
		"category": ["general"],
		"published": "2025-05-07 00:04:14 +0000"
	},
	{
		"id": "a469b981-0060-44bb-88b9-4d7e588660af",
		"title": "Teamsters boss praises Trump foreign film tariff, condemns Hollywood's 'un-American addiction to outsourcing'",
		"description": "Teamsters General President Sean M. O'Brien and Teamsters Motion Picture Division Director Lindsay Dougherty praised President Donald Trump's call to place a 100% tariff on films produced in other countries.In a Truth Social post on Sunday, Trump wrote that the \"Movie Industry in America is DYING a ...",
		"url": "https://www.foxnews.com/media/teamsters-boss-praises-trump-foreign-film-tariff-condemns-hollywoods-un-american-addiction-outsourcing",
		"author": "foxnews",
		"image": "https://static.foxnews.com/foxnews.com/content/uploads/2024/01/trump-teamsters.jpg",
		"language": "en",
		"category": ["general"],
		"published": "2025-05-07 00:00:32 +0000"
	},
	{
		"id": "9c09e645-fd16-474b-82f2-50530bb268aa",
		"title": "Trump touts $9 trillion in new U.S. investment. The numbers don't add up.",
		"description": "What to know about Trump's explosive weekend interview, plan to put tariffs on movies\n\nAfter President Trump was pressed on rising consumer prices and slowing economic growth, he defended his tariff p...",
		"url": "https://www.cbsnews.com/news/fact-check-trump-9-trillion-us-investments/",
		"author": "Laura",
		"image": "https://assets1.cbsnewsstatic.com/hub/i/r/2025/03/07/53e24812-193f-422a-af96-db40bb1039cb/thumbnail/1200x630/6ab50ef96ca6e38f686cb6076f7ebc60/trump3.jpg?v=8782d831dd587e69db5d043c0a4c5f4b",
		"language": "en",
		"category": ["politics", "world"],
		"published": "2025-05-06 23:47:09 +0000"
	},
	{
		"id": "e4076eb8-7964-4334-9f9e-1189bfcb0fa3",
		"title": "Tom Brady gives positive assessment of Raiders rookie Cam Miller's NFL future: report",
		"description": "Former Boise State star running back Ashton Jeanty headlined the Las Vegas Raiders' 2025 NFL Draft class. But the franchise's sixth-round selection caught Tom Brady's eye.Cam Miller, who won two FCS national championships during his standout career at North Dakota State, was the 215th overall pick i...",
		"url": "https://www.foxnews.com/sports/tom-brady-gives-positive-assessment-raiders-rookie-cam-millers-first-nfl-season-report",
		"author": "foxnews",
		"image": "https://static.foxnews.com/foxnews.com/content/uploads/2025/05/north-dakota-state-cam-miller.jpg",
		"language": "en",
		"category": ["general"],
		"published": "2025-05-06 23:44:32 +0000"
	},
	{
		"id": "6ea0d199-2a13-4b67-b719-90fe6d3038fe",
		"title": "New Pulitzer Prize winner disparaged Israelis kidnapped by Hamas on Oct 7, questioned their 'hostage' status",
		"description": "FIRST ON FOX - The Pulitzer board awarded a prize Monday to a Palestinian poet and author who frequently disparaged Israeli hostages on social media, referring to them as \"killers\" and denying they were tortured under Hamas captivity.Mosab Abu Toha was awarded a Pulitzer Prize for his essays publish...",
		"url": "https://www.foxnews.com/media/new-pulitzer-prize-winner-disparaged-israelis-kidnapped-hamas-oct-7-questioned-hostage-status",
		"author": "foxnews",
		"image": "https://static.foxnews.com/foxnews.com/content/uploads/2025/05/mosab-abu-toha.jpg",
		"language": "en",
		"category": ["general"],
		"published": "2025-05-06 23:35:26 +0000"
	},
	{
		"id": "0ef52108-7917-4e6b-93b5-9436187e6089",
		"title": "US officials to meet with Chinese counterparts in Switzerland amid trade war",
		"description": "Top officials with the Trump administration are expected to meet with a high-level Chinese delegation this week in Switzerland, marking the first major talks between the two countries since President Donald Trump ignited a trade war based on tariffs on imports.U.S. Treasury Secretary Scott Bessent a...",
		"url": "https://www.foxnews.com/politics/us-officials-meet-chinese-counterparts-switzerland-amid-trade-war",
		"author": "foxnews",
		"image": "https://static.foxnews.com/foxnews.com/content/uploads/2025/05/treasury-sec-scott-bessent.png",
		"language": "en",
		"category": ["general"],
		"published": "2025-05-06 23:33:49 +0000"
	},
	{
		"id": "fbec9aaa-4d8f-443a-9df4-e6f4065f0605",
		"title": "Senate Democrats rally against crypto bill amid criticism of Trump's ties to the industry",
		"description": "Washington — Senate Democrats are rebelling against a crypto regulation bill, putting the first-of-its-kind legislation in jeopardy ahead of a possible key vote on it later this week.\n\nThe bill, known...",
		"url": "https://www.cbsnews.com/news/senate-democrats-genius-act-stablecoin-crypto-bill-trump/",
		"author": "Caitlin",
		"image": "https://assets1.cbsnewsstatic.com/hub/i/r/2025/05/06/6bf463ee-2c7d-417e-931d-ff071f372102/thumbnail/1200x630/64c68a86c087dac87fc45d4c15a8fbec/gettyimages-2213613719.jpg?v=8782d831dd587e69db5d043c0a4c5f4b",
		"language": "en",
		"category": ["politics", "world"],
		"published": "2025-05-06 23:31:37 +0000"
	},
	{
		"id": "6103584c-d22a-4d48-977e-562ae8cb0000",
		"title": "California AG takes stance on Menendez brothers prosecutor staying on case amid resentencing battle",
		"description": "California Attorney General Rob Bonta is pushing back against Erik and Lyle Menendez's defense team's request to remove the Los Angeles District Attorney's office from their resentencing case. The brothers' attorneys have argued that the DA's office has shown bias against them and violated Marsy's L...",
		"url": "https://www.foxnews.com/us/california-ag-takes-stance-menendez-brothers-prosecutor-staying-case-amid-resentencing-battle",
		"author": "foxnews",
		"image": "https://static.foxnews.com/foxnews.com/content/uploads/2024/10/menendez-brothers-serving-life-for-parents-shotgun-slayings-1.jpg",
		"language": "en",
		"category": ["general"],
		"published": "2025-05-06 23:21:06 +0000"
	},
	{
		"id": "ba1f9eae-77f8-46a1-9bbb-dda1bad29e8f",
		"title": "Trump admin reinstates 9/11 survivors program staff following HHS reorganization",
		"description": "FIRST ON FOX: The Trump administration's Health and Human Services Department (HHS) sent out reinstatement notices to staff members who were part of a federal healthcare program for 9/11 survivors, following a reduction in force at HHS and its subagencies as part of Trump's efforts to optimize the f...",
		"url": "https://www.foxnews.com/politics/trump-admin-reinstates-9-11-survivors-program-staff-following-hhs-reorganization",
		"author": "foxnews",
		"image": "https://static.foxnews.com/foxnews.com/content/uploads/2025/05/worldtradecenterhealthprogram2_main.jpg",
		"language": "en",
		"category": ["general"],
		"published": "2025-05-06 23:09:10 +0000"
	}
]
